### ISSUE TITLE
Awesome books with objects

### ISSUE THREAD

**Issue by KayLemba** [thecodechaser/awesome-books#2]
Hello Ranjeet & Emmanuel,
 Everything looks great. 💯  congratulations 😄 

Happy coding 
cheers 🍾

**Comment by thecodechaser** [comment]
> Hello Ranjeet & Emmanuel,  Everything looks great. 💯 congratulations 😄
> 
> Happy coding cheers 🍾

Hello @KayLemba 
Thank you for your feedback, It will help our team to improve more.

**Comment by KayLemba** [comment]
@thecodechaser  you are most welcome
